

services:

  db:
 
    image: redis

    ports:
      - '6379:6379'

    command: redis-server



  micro:

    image: ak1990/ak1990hub:micro

    ports:
      - '3001:3001'

    environment:
      - REDIS_URL=redis://db
 
    depends_on:
      - db
