
services:

  db:
 
    image: redis

    ports:
      - '6379:6379'

    command: redis-server



  micro:

    image: ak1990/ak1990hub:micro

    ports:
      - 3001:3001

    environment:
      - REDIS_URL=redis://db
 
    depends_on:
      - db




  library:

    image: ak1990/ak1990hub:library

    ports:
      - 3000:3000

    environment:
      - MICRO_URL=http://micro
 
    depends_on:
      - micro



